var express = require('express')
var bodyparser = require('body-parser')
var app = express()
app.use(bodyparser.urlencoded({extended: false}))
app.put('/message/:id', function(req, res) {
  var hash = require('crypto')
      .createHash('sha1')
      .update(new Date().toDateString() + req.params.id)
      .digest('hex')
  res.send(hash)
})
app.listen(process.argv[2])
